package commons;

public class SNFFields {
	private static final String[] NFE = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "CD_CHAV_ACES_NFE", "CD_STAT",
			"CD_UNID_NEGC", "CD_LOCA_IMPS", "DS_NATU_OPER", "CD_PART_ORIG", "NR_PEDI_ORIG", "NR_PEDI_CLIE_ORIG",
			"CD_INDI_FRMA_PGTO", "DT_EMIS_DOCT_FISC", "DT_ENTD_SAID_MERC", "TP_DOCT_FISC", "CD_MUNI_FATO_GRDR_ORGL",
			"CD_MUNI_FATO_GRDR", "CD_AMBI", "CD_FIND_EMIS_NFE", "FL_EMIT_CNPJ_CPF", "NM_EMIT", "NM_FNTS_EMIT",
			"DS_LOGR_EMIT", "DS_NURO_LOGR_EMIT", "DS_CPLM_LOGR_EMIT", "DS_BAIR_LOGR_EMIT", "CD_MUNI_EMIT_ORGL",
			"CD_MUNI_EMIT", "NM_MUNI_EMIT", "SG_ESTD_EMIT", "NR_CEP_EMIT", "NR_FONE_EMIT", "NR_FAX_EMIT",
			"CD_INSC_ESTL_EMIT", "CD_INSC_ESTL_SUBS_TRIB", "CD_INSC_MUNI_EMIT", "CD_CNAE_FISC", "CD_CNPJ_DEST",
			"CD_CPF_DEST", "NM_DEST", "DS_LOGR_DEST", "DS_NURO_LOGR_DEST", "DS_CPLM_LOGR_DEST", "DS_BAIR_LOGR_DEST",
			"CD_MUNI_DEST_ORGL", "CD_MUNI_DEST", "NM_MUNI_DEST", "SG_ESTD_DEST", "NR_CEP_DEST", "CD_PAIS_DEST_ORGL",
			"CD_PAIS_DEST", "NM_PAIS_DEST", "NR_FONE_DEST", "CD_INSC_ESTL_DEST", "CD_INSC_SUFR_DEST", "CD_CNPJ_RETI",
			"DS_LOGR_RETI", "DS_NURO_LOGR_RETI", "DS_CPLM_LOGR_RETI", "DS_BAIR_LOGR_RETI", "CD_MUNI_RETI_ORGL",
			"CD_MUNI_RETI", "NM_MUNI_RETI", "SG_ESTD_RETI", "CD_CNPJ_ENTR", "DS_LOGR_ENTR", "DS_NURO_LOGR_ENTR",
			"DS_CPLM_LOGR_ENTR", "DS_BAIR_LOGR_ENTR", "CD_MUNI_ENTR_ORGL", "CD_MUNI_ENTR", "NM_MUNI_ENTR",
			"SG_ESTD_ENTR", "VL_TOTA_BASE_CALC_ICMS", "VL_TOTA_ICMS", "VL_TOTA_BASE_CALC_ICMS_SUBS",
			"VL_TOTA_ICMS_SUBS", "VL_TOTA_PROD_SERV", "VL_TOTA_FRET", "VL_TOTA_SEGR", "VL_TOTA_DSCT",
			"VL_TOTA_IMPT_IMPO", "VL_TOTA_IPI", "VL_TOTA_PIS", "VL_TOTA_COFS", "VL_TOTA_DESP_ACSS", "VL_TOTA_NFE",
			"VL_TOTA_SERV", "VL_TOTA_BASE_CALC_ISS", "VL_TOTA_ISS", "VL_TOTA_PIS_SERV", "VL_TOTA_COFS_SERV",
			"VL_TOTA_RETD_PIS", "VL_TOTA_RETD_COFS", "VL_TOTA_RETD_CSLL", "VL_TOTA_BASE_CALC_IRRF", "VL_TOTA_RETD_IRRF",
			"VL_TOTA_BASE_CALC_RETD_PRVD", "VL_TOTA_RETD_PRVD", "CD_MODA_FRET", "CD_CNPJ_TRAN", "CD_CPF_TRAN",
			"NM_TRAN", "CD_INSC_ESTL_TRAN", "DS_ENDR_CMPL_TRAN", "NM_MUNI_TRAN", "SG_ESTD_TRAN", "VL_SERV_TRAN",
			"VL_BASE_CALC_ICMS_TRAN", "PC_ICMS_TRAN", "VL_ICMS_RETD_TRAN", "CD_CFOP_TRAN",
			"CD_MUNI_FATO_GRDR_TRAN_ORGL", "CD_MUNI_FATO_GRDR_TRAN", "DS_PLAC_VEIC", "SG_ESTD_VEIC",
			"CD_REGT_NACI_TRAN_CARG", "NR_FTRA", "VL_ORGL_FTRA", "VL_DSCT_FTRA", "VL_LIQD_FTRA", "DS_INFO_ADCI_FISC",
			"DS_INFO_ADCI_CTBT", "SG_ESTD_EMBQ", "DS_LOCA_EMBQ", "DS_NOTA_EMPE", "CD_PEDI_CPRA", "CD_CTRT_CPRA",
			"FL_TAXA_ZERO", "DT_SOLI_CNCT", "DS_JUST_CNCT", "DT_RECB", "NR_PROT_NFE", "CD_VERF_NFE", "CD_STAT_APLI",
			"DS_STAT_APLI", "NR_PROT_CNCT", "CD_STAT_APLI_CNCT", "DS_STAT_APLI_CNCT", "CD_IDEN_INUT", "NR_PROT_INUT",
			"CD_USER_MANU", "TS_MANU", "DS_DADO_ADIC", "DS_HORA_SAID", "DS_EMAI_ENVI_XML", "DS_EMAI_ENVI_DANF",
			"NR_CARG", "CD_FRMA_EMIS_NFE", "CD_VERS_ANVE", "CD_TRNS_ANVE", "NM_TRNS_ANVE", "CD_RECP_ANVE",
			"NM_RECP_ANVE", "CD_ESPC_NOTA_ANVE", "CD_FABR_ENTR_ANVE", "DT_PREV_ENTR_ANVE", "NR_INVC_ANVE",
			"TP_LAYT_ANVE", "CD_REGM_TRIB", "DS_EMAI_DEST", "CD_CPF_RETI", "CD_CPF_ENTR", "CD_TIPO_FRET",
			"DS_EMAI_ENVI_XML_TRAN", "CD_VEIC_TRAN", "CD_TIPO_CARG", "NR_DOCT_REFR_ERP", "CD_VERS_NFE",
			"VL_TOTA_IMPT_NFE", "FL_CTRL_IMPR_NFE_REFE", "CD_ID_DEST", "CD_FRMT_IMPS_DANF", "CD_INDI_CONS_FINL",
			"CD_INDI_PRES", "CD_INDI_DEST_ESTR", "CD_INDI_IE_DEST", "CD_INSC_MUNI_TOMD", "VL_TOTA_ICMS_DESN",
			"DT_PRES_SERV", "VL_TOTA_DEDC_BASE_ISS", "VL_TOTA_OUTR_RETN_ISS", "VL_TOTA_DSCT_INCD_ISS",
			"VL_TOTA_DSCT_COND_ISS", "VL_TOTA_RETR_ISS", "CD_REGM_ESPC_TRIB", "VL_TOTA_ICMS_PART_UF_DEST",
			"VL_TOTA_ICMS_PART_UF_ORIG", "VL_TOTA_ICMS_FCP_DEST", "VL_TOTA_FCP", "VL_TOTA_FCP_ST",
			"VL_TOTA_FCP_ANTR_ST", "VL_TOTA_IPI_DEVO", "DS_QR_CODE", "DS_URL_CHAV" };

	private static final String[] NFE_REFE_NOTA_FISC = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE",
			"CD_CNPJ_EMIT_NFE", "CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "CD_ESTD_EMIT",
			"DT_AAMM_EMIS_NOTA_FISC", "CD_CNPJ_EMIT", "CD_MODL_DOCT_FISC", "CD_SERE_DOCT_FISC", "NR_DOCT_FISC",
			"CD_USER_MANU", "TS_MANU", "NR_SEQA_NFE_REFE", "TP_REFE", "CD_CHAV_ACES_NFE_REFE", "CD_CPF_EMIT",
			"CD_INSC_ESTL_EMIT_PRDT", "CD_CHAV_ACES_CTE_REFE", "NR_ORDE_SEQA_ECF", "NR_CTDR_ORDE_OPER" };

	private static final String[] NFE_PROD = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_ITEM", "CD_PROD_SERV", "CD_GTIN",
			"DS_PROD_SERV", "CD_NCM", "CD_EX_TIPI", "CD_GENE_PROD_SERV", "CD_CFOP", "CD_UNID_COML", "QT_COML",
			"VL_UNIT_COML", "VL_TOTA_BRTO_PROD_SERV", "CD_GTIN_TRBV", "CD_UNID_TRBV", "QT_TRBV", "VL_UNIT_TRBV",
			"VL_TOTA_FRET", "VL_TOTA_SEGR", "VL_TOTA_DSCT", "CD_PROD_SERV_ORGL", "CD_ORIG_MERC_ICMS",
			"CD_SITC_TRIB_ICMS", "CD_MODA_BASE_CALC_ICMS", "VL_BASE_CALC_ICMS", "PC_ICMS", "VL_ICMS",
			"CD_MODA_BASE_CALC_ICMS_SUBS", "PC_MARG_ADIC_ICMS_SUBS", "PC_REDU_BASE_ICMS_SUBS", "VL_BASE_CALC_ICMS_SUBS",
			"PC_ICMS_SUBS", "VL_ICMS_SUBS", "PC_REDU_BASE_CALC_ICMS", "CD_CLAE_ENQD_IPI", "CD_CNPJ_PRDT",
			"CD_SELO_CTRL_IPI", "QT_SELO_CTRL_IPI", "CD_ENQD_LEGL_IPI", "CD_SITC_TRIB_IPI", "VL_BASE_CALC_IPI",
			"QT_UNID_PADR", "VL_UNID_TRBV", "PC_IPI", "VL_IPI", "VL_BASE_CALC_IMPT_IMPO", "VL_DESP_ADUA",
			"VL_IMPT_IMPO", "VL_IMPT_OPER_FINC", "CD_SITC_TRIB_PIS", "VL_BASE_CALC_PIS", "PC_PIS", "VL_PIS",
			"QT_BASE_CALC_PIS", "VL_ALIQ_PIS", "VL_BASE_CALC_PIS_SUBT_TRIB", "PC_PIS_SUBT_TRIB",
			"QT_BASE_CALC_PIS_SUBT_TRIB", "VL_ALIQ_PIS_SUBT_TRIB", "VL_PIS_SUBT_TRIB", "CD_SITC_TRIB_COFS",
			"VL_BASE_CALC_COFS", "PC_COFS", "VL_COFS", "QT_BASE_CALC_COFS", "VL_ALIQ_COFS",
			"VL_BASE_CALC_COFS_SUBT_TRIB", "PC_COFS_SUBT_TRIB", "QT_BASE_CALC_COFS_SUBT_TRIB", "VL_ALIQ_COFS_SUBT_TRIB",
			"VL_COFS_SUBT_TRIB", "VL_BASE_CALC_ISS", "PC_ISS", "VL_ISS", "CD_MUNI_FATO_GRDR_ISS", "CD_LIST_SERV",
			"DS_INFO_ADCI_PROD", "CD_USER_MANU", "TS_MANU", "PC_DSCT", "CD_ITEM_CLIE_ANVE", "NR_PEDI_CPRA_CLIE_ANVE",
			"SG_TIPO_PEDI_ANVE", "CD_ALTR_TECN_ITEM_ANVE", "TP_FCMT_ANVE", "CD_UNID_MEDD_CLIE_ANVE",
			"DT_VALD_DESE_ANVE", "NR_PEDI_REVD_ANVE", "CD_PAIS_EXPO_ANVE", "QT_PESO_BRTO_ANVE", "QT_PESO_LIQD_ANVE",
			"TP_CHMD_ANVE", "NR_CHMD_ANVE", "DT_CHMD_ANVE", "QT_EMBL_CHMD_ANVE", "QT_ITEM_CHMD_ANVE",
			"CD_LOCA_ENTR_DOCA_ANVE", "CD_PONT_USO_ANVE", "TP_TRNP_ANVE", "CD_LOTE_PROD_ANVE", "CD_CTRL_INIL_PROD_ANVE",
			"NR_NOTA_EMBL_ASSC_ANVE", "CD_SERE_NOTA_ASSC_ANVE", "CD_EMBL_ANVE", "CD_AUTR_FATR_ANVE",
			"FL_IMPR_DADO_ADIC_PROD", "VL_OUTR_DESP_ACES", "FL_VALR_ITEM_SOMA_VALR_NFE", "NR_PEDI_CPRA ",
			"NR_PEDI_CPRA_ITEM", "CD_MOTI_DESO_ICMS", "VL_BASE_CALC_ICMS_SUBS_RETD", "VL_ICMS_SUBS_RETD",
			"VL_BASE_CALC_ICMS_SUBS_DEST", "VL_ICMS_SUBS_DEST", "TP_ICMS_SUBS", "PC_BASE_CALC_OPER_PROP",
			"SG_ESTD_ICMS_ST", "CD_SITC_OPER_SIMP_NACI", "PC_CRED_SIMP_NACI", "VL_CRED_SIMP_NACI", "CD_TRIB_ISS",
			"QT_PESO_LIQD", "QT_PESO_BRTO", "CD_CLAS_RISC", "QT_EMBA_ITEM", "DS_EMBA_ITEM", "VL_TOTA_IMPT_ITEM",
			"NR_FCI", "CD_NVE", "NR_RECO", "VL_ICMS_DESN", "VL_ICMS_OPER", "PC_DIFR_ICMS", "VL_ICMS_DIFR",
			"VL_DEDC_BASE_ISS", "VL_OUTR_RETN_ISS", "VL_DSCT_INCD_ISS", "VL_DSCT_COND_ISS", "VL_RETR_ISS", "CD_IND_ISS",
			"CD_SERV_MUNI", "CD_MUNI_INCD_ISS", "CD_PAIS_PRES_SERV", "NR_PROC_EXGB_ISS", "CD_IND_ICTV_ISS",
			"PC_MERC_DEVO", "VL_IPI_DEVO", "CD_CEST", "VL_BASE_CALC_ICMS_UF_DEST", "PC_ICMS_UF_DEST", "PC_ICMS_UF_INTE",
			"PC_ICMS_PART_UFS", "VL_ICMS_PART_UF_DEST", "VL_ICMS_PART_UF_ORIG", "PC_ICMS_FCP_DEST  ",
			"VL_ICMS_FCP_DEST", "VL_BASE_CALC_FCP_UF_DEST", "VL_BASE_CALC_FCP", "PC_FCP", "VL_FCP",
			"VL_BASE_CALC_FCP_ST", "PC_FCP_ST", "VL_FCP_ST", "VL_BASE_CALC_FCP_ANTR_ST", "PC_FCP_ANTR_ST",
			"VL_FCP_ANTR_ST", "PC_ICMS_ST_CONS_FINL", "FL_INDI_ESCL_RELV", "CD_CNPJ_FABR_MERC", "CD_BENI_FISC_UF" };

	private static final String[] NFE_DI = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_ITEM", "NR_DOCT_IMPO",
			"DT_REGT_DOCT_IMPO", "DS_LOCA_DESE", "SG_ESTD_DESE_ADUA", "DT_DESE_ADUA", "CD_EXPO", "CD_USER_MANU",
			"TS_MANU", "CD_TP_VIA_TRAN", "VL_AFRM", "CD_TP_INTE", "CD_CNPJ_ADQR", "SG_ESTD_ADQR" };

	private static final String[] NFE_ADI = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_ITEM", "NR_DOCT_IMPO", "NR_ADI",
			"NR_ADI_ITEM", "CD_FABR_ETRG", "VL_DSCT_ITEM_ADI", "CD_USER_MANU", "TS_MANU", "NR_DRAW" };

	private static final String[] NFE_VEIC = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_ITEM", "TP_OPER_VEIC",
			"CD_CHAS_VEIC", "CD_COR_VEIC", "DS_COR_VEIC", "DS_POTE_MOTR_VEIC", "DS_CM3_VEIC", "DS_PESO_LIQD_VEIC",
			"DS_PESO_BRTO_VEIC", "DS_SERE_VEIC", "DS_TIPO_COMB_VEIC", "DS_NURO_MOTR_VEIC", "CD_CMKG_VEIC",
			"DS_DTAN_EIXO_VEIC", "CD_RNAV_VEIC", "DT_ANO_MODL_FABR_VEIC", "DT_ANO_FABR_VEIC", "TP_PINT_VEIC", "TP_VEIC",
			"CD_ESPC_VEIC", "CD_COND_VIN_VEIC", "CD_COND_VEIC", "CD_MARC_MODL_VEIC", "CD_USER_MANU", "TS_MANU",
			"CD_COR_VEIC_DENT", "QT_CAPC_LOTA", "TP_REST" };

	private static final String[] NFE_MEDC = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_ITEM", "NR_LOTE_MEDC",
			"QT_PROD_LOTE_MEDC", "DT_FABR_MEDC", "DT_VALD_MEDC", "VL_PREC_MAXM_CSMD", "CD_USER_MANU", "TS_MANU",
			"CD_PROD_ANVS" };

	private static final String[] NFE_ARMA = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_ITEM", "TP_ARMA", "NR_SERE_ARMA",
			"NR_SERE_CANO_ARMA", "DS_CPLT_ARMA", "CD_USER_MANU", "TS_MANU" };

	private static final String[] NFE_REBQ = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "DS_PLAC_VEIC", "SG_ESTD_VEIC",
			"CD_REGT_NACI_TRAN_CARG", "CD_USER_MANU", "TS_MANU", "DS_VAGA", "DS_BALS" };

	private static final String[] NFE_VOLU = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_SEQA_VOLU", "QT_VOLU_TRAN",
			"DS_ESPC_VOLU_TRAN", "DS_MARC_VOLU_TRAN", "DS_NUMC_VOLU_TRAN", "QT_PESO_LIQD_VOLU_TRAN",
			"QT_PESO_BRTO_VOLU_TRAN", "CD_USER_MANU", "TS_MANU" };

	private static final String[] NFE_LACR = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_SEQA_VOLU", "NR_LACR",
			"CD_USER_MANU", "TS_MANU" };

	private static final String[] NFE_DUPL = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_SEQA_DUPL", "NR_DUPL",
			"DT_VCTO_DUPL", "VL_DUPL", "CD_USER_MANU", "TS_MANU" };

	private static final String[] NFE_COMB = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_ITEM", "CD_PROD_ANP", "CD_CODF",
			"QT_COMB_TMPR_AMBI", "QT_BASE_CALC_CIDE", "VL_ALIQ_CIDE", "VL_CIDE", "VL_BASE_CALC_ICMS", "VL_ICMS",
			"VL_BASE_CALC_ICMS_SUBT_TRIB_RETD", "VL_ICMS_SUBT_TRIB_RETD", "VL_BASE_CALC_ICMS_SUBT_TRIB_DEST",
			"VL_ICMS_SUBT_TRIB_DEST", "VL_BASE_CALC_ICMS_SUBT_TRIB_CONS", "VL_ICMS_SUBT_TRIB_CONS", "SG_ESTD_CONS",
			"CD_USER_MANU", "TS_MANU", "PC_MIX_GN", "DS_PROD_ANP", "PC_GLP_DERV_PETR", "PC_GLP_GAS_NACI",
			"PC_GLP_GAS_IMPO", "VL_PRTD", "NR_BICO_UTLZ", "NR_BOMB_ITLG_BICO", "NR_TANQ_ITLG_BICO", "VL_ENCE_INIC_ABAS",
			"VL_ENCE_FINL_ABAS" };

	private static final String[] NFE_OBSV_CTBT = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE",
			"CD_CNPJ_EMIT_NFE", "CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_SEQA",
			"CD_IDEN_CAMP", "DS_CNTU_CAMP", "CD_USER_MANU", "TS_MANU" };

	private static final String[] NFE_OBSV_FISC = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE",
			"CD_CNPJ_EMIT_NFE", "CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_SEQA",
			"CD_IDEN_CAMP", "DS_CNTU_CAMP", "CD_USER_MANU", "TS_MANU" };

	private static final String[] NFE_PROC_REFE = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE",
			"CD_CNPJ_EMIT_NFE", "CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_SEQA",
			"CD_IDEN_PROC", "CD_ORIG_PROC", "CD_USER_MANU", "TS_MANU" };

	private static final String[] NFE_CANC = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_SEQA_CNCT", "CD_STAT_CNCT",
			"DT_SOLI_CNCT", "DS_JUST_CNCT", "CD_USER_MANU", "TS_MANU" };

	private static final String[] NFE_CCE = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_SEQA_EVET", "CD_STAT_CCE",
			"DS_CCE", "CD_USER_MANU", "TS_MANU" };

	private static final String[] NFE_SOLT_EVET = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE",
			"CD_CNPJ_EMIT_NFE", "CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "TP_EVET",
			"NR_SEQA_EVET", "CD_AMBI", "CD_CHAV_ACES_NFE", "CD_ORGA_REPC_EVET", "CD_CNPJ_EVET", "CD_CPF_EVET",
			"DT_EVET", "DS_EVET", "DS_JUST_EVET", "CD_STAT", "CD_VERF_NFE", "CD_STAT_APLI", "DS_STAT_APLI",
			"DS_EMAI_DEST", "DT_RECB_EVET", "NR_PROT_EVET", "DS_ERRO_VALD", "CD_USER_MANU", "TS_MANU" };

	private static final String[] NFE_AUTR_DOWN = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE",
			"CD_CNPJ_EMIT_NFE", "CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_SEQA_AUTR",
			"CD_CNPJ_AUTR", "CD_CPF_AUTR", "CD_USER_MANU", "TS_MANU" };

	private static final String[] NFE_EXPT = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_ITEM", "NR_DRAW", "NR_RE",
			"CD_CHAV_ACES_NFE_EXPT", "QT_EXPT", "CD_USER_MANU", "TS_MANU", "NR_SEQA_EXPT" };

	private static final String[] NFE_FRMA_PGTO = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE",
			"CD_CNPJ_EMIT_NFE", "CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_ITEM",
			"CD_PGTO", "VL_PGTO", "CD_CNPJ_CRED_CART", "CD_BNDR_CART", "DS_AUT_CART", "CD_USER_MANU", "TS_MANU",
			"TP_INTG_PGTO", "VL_TROC" };

	private static final String[] NFE_NVE = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_ITEM", "CD_NVE", "CD_USER_MANU",
			"TS_MANU" };

	private static final String[] NFE_SOLT_PEDI_PROR = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE",
			"CD_CNPJ_EMIT_NFE", "CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "TP_EVET",
			"NR_SEQA_EVET", "CD_AMBI", "CD_CHAV_ACES_NFE", "CD_ORGA_REPC_EVET", "CD_CNPJ_EVET", "CD_CPF_EVET",
			"DT_EVET", "DS_EVET", "NR_PROT_EVET_CANC", "NR_SEQA_EVET_CANC", "CD_STAT", "CD_STAT_APLI", "DS_STAT_APLI",
			"CD_STAT_PRAZ", "CD_STAT_CNCT", "DS_JUST_STAT_CNCT", "DS_JUST_STAT_OUTR_CNCT", "DS_EMAI_DEST",
			"DT_RECB_EVET", "NR_PROT_EVET", "DS_ERRO_VALD", "CD_USER_MANU", "TS_MANU" };

	private static final String[] NFE_SOLT_PEDI_ITEM = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE",
			"CD_CNPJ_EMIT_NFE", "CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "TP_EVET",
			"NR_SEQA_EVET", "NR_ITEM", "QTDE_ITEM", "CD_STAT_ITEM", "DS_JUST_STAT", "DS_JUST_STAT_OUTR", "DT_EVET",
			"DS_EVET", "CD_STAT", "CD_STAT_APLI", "DS_STAT_APLI", "DS_EMAI_DEST", "DT_RECB_EVET", "NR_PROT_EVET",
			"DS_ERRO_VALD", "CD_USER_MANU", "TS_MANU" };

	private static final String[] NFE_RSTR = new String[] { "CD_ESTD_EMIT_NFE", "DT_AAMM_EMIS_NFE", "CD_CNPJ_EMIT_NFE",
			"CD_MODL_DOCT_FISC_NFE", "CD_SERE_DOCT_FISC_NFE", "NR_DOCT_FISC_NFE", "NR_ITEM", "NR_SEQA_RSTR",
			"NR_LOTE_PROD", "QT_PROD_LOTE", "DT_FABR_PROD", "DT_VALD_PROD", "CD_AGRG_PROD", "CD_USER_MANU", "TS_MANU" };

	private static final String[] LAYOUTS = new String[] { "201", "203", "204", "205", "206", "207", "208", "209",
			"210", "211", "212", "213", "214", "215", "216", "217", "220", "221", "222", "225", "226", "227", "228",
			"237", "238", "239"};

	public static String[] getNfe() {
		return NFE;
	}

	public static String[] getNfeRefeNotaFisc() {
		return NFE_REFE_NOTA_FISC;
	}

	public static String[] getNfeProd() {
		return NFE_PROD;
	}

	public static String[] getNfeDi() {
		return NFE_DI;
	}

	public static String[] getNfeAdi() {
		return NFE_ADI;
	}

	public static String[] getNfeVeic() {
		return NFE_VEIC;
	}

	public static String[] getNfeMedc() {
		return NFE_MEDC;
	}

	public static String[] getNfeArma() {
		return NFE_ARMA;
	}

	public static String[] getNfeRebq() {
		return NFE_REBQ;
	}

	public static String[] getNfeVolu() {
		return NFE_VOLU;
	}

	public static String[] getNfeLacr() {
		return NFE_LACR;
	}

	public static String[] getNfeDupl() {
		return NFE_DUPL;
	}

	public static String[] getNfeComb() {
		return NFE_COMB;
	}

	public static String[] getNfeObsvCtbt() {
		return NFE_OBSV_CTBT;
	}

	public static String[] getNfeObsvFisc() {
		return NFE_OBSV_FISC;
	}

	public static String[] getNfeProcRefe() {
		return NFE_PROC_REFE;
	}

	public static String[] getNfeCanc() {
		return NFE_CANC;
	}

	public static String[] getNfeCce() {
		return NFE_CCE;
	}

	public static String[] getNfeSoltEvet() {
		return NFE_SOLT_EVET;
	}

	public static String[] getNfeAutrDown() {
		return NFE_AUTR_DOWN;
	}

	public static String[] getNfeExpt() {
		return NFE_EXPT;
	}

	public static String[] getNfeFrmaPgto() {
		return NFE_FRMA_PGTO;
	}

	public static String[] getNfeNve() {
		return NFE_NVE;
	}

	public static String[] getNfeSoltPediPror() {
		return NFE_SOLT_PEDI_PROR;
	}

	public static String[] getNfeSoltPediItem() {
		return NFE_SOLT_PEDI_ITEM;
	}

	public static String[] getNfeRstr() {
		return NFE_RSTR;
	}

	public static String[] getLayouts() {
		return LAYOUTS;
	}

}
